name: movecare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.6.0
  qr_flutter: ^4.1.0 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ruta.png
    - assets/movecare.png
    - assets/icono_google.png
    - assets/fondo_welcome.png
    - assets/mapa.png
    - assets/conductor.png
    - assets/pasajero.png
    - assets/auditiva.png
    - assets/visual.png
    - assets/control_voz.png
    - assets/silla_ruedas.png
    - assets/ine_anverso.png
    - assets/ine_reverso.png
    - assets/obesidad.png
    - assets/tarjeta_credito.png
    - assets/tarjeta_debito.png
    - assets/tarjeta.png
    - assets/tercera_edad.png
    - assets/home_icon.png
    - assets/ubi_icon.png
    - assets/historial_icon.png
    - assets/perfil_icon.png
    - assets/movecare_principal.png